### PR TITLE
Add get_name to retrieve human-readable Tz names

### LINKED ISSUE #6: Human readable names of the time-zones.
Printing the TimeZone in debug mode (i.e. using `{:?}` formatter) shows a correct name of the zone but that does not seem like a kosher way of arriving at the names.

I couldn't find another way. Since the `Tz` is an `enum`, it cannot provide an attribute like `.name` (re: #1). Also, providing a `.to_string()` (i.e. implementing a `Display` trait), is tricky because a time-zone can have several names depending on the context, e.g. both `Asia/Kolkata` and `IST` can be seen as _expected_ outputs of `.to_string()`.

Perhaps the `Debug` implementation can be moved to a function `get_name` which returns a `String` and then implementation of `Debug` could be:

```
impl Debug for Tz {
    fn fmt(&self, f: &mut Formatter) -> Result<(), Error> {
        write!(f, "{}", get_name(self))
    }
}
```

What do you think?

### PR DESCRIPTION
**Pull request by musically-ut**
Fixes #6.

Sorry, but it seems that some whitespace changes also made it through. I can get rid of those if they bother you.

### CODE REVIEW

**Comment by djzin** [comment]
Looks good, shouldn't this be an inherent impl on `Tz`, though? Like `London.name() == "London"` Seems more natural to me. What are your thoughts?

**Comment by musically-ut** [comment]
Something like:

```rust
trait NamedTz {
    fn name(self) -> &'static str;
}

impl NamedTz for Tz {
    fn name(self) -> &'static str {
        match self {
            Tz::London => "Europe/London",
            // ...
        }
    }
}
```

?

Any preference for the `trait` name?

**Comment by musically-ut** [comment]
I hadn't realize that `impl` can be written without an explicit name for the trait. In that case, this indeed does look like a better way to implement this change.

Any thoughts?

**Comment by djzin** [comment]
looks perfect, will merge this later today when I have a chance to test

**Pull request merged**
